package com.ems.entity;
// Generated Aug 11, 2019 12:49:44 AM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.*;
import lombok.*;

/**
 * Departments generated by hbm2java
 */

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Entity
@Table(name = "departments", uniqueConstraints = @UniqueConstraint(columnNames = "dept_name"))
public class Departments implements java.io.Serializable {
    @Id
    @Column(name = "dept_no", unique = true, nullable = false, length = 4)
    private String deptNo;

    @Column(name = "dept_name", unique = true, nullable = false, length = 40)
    private String deptName;

    /*
     * @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments") public
     * Set<DeptEmp> getDeptEmps() { return this.deptEmps; }
     *
     * public void setDeptEmps(Set<DeptEmp> deptEmps) { this.deptEmps = deptEmps; }
     *
     * @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments") public
     * Set<DeptManager> getDeptManagers() { return this.deptManagers; }
     *
     * public void setDeptManagers(Set<DeptManager> deptManagers) {
     * this.deptManagers = deptManagers; }
     */
}
