package com.ems.entity;
// Generated Aug 11, 2019 12:49:44 AM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.*;
import lombok.*;

import java.util.Date;

/**
 * DeptEmp generated by hbm2java
 */

@NoArgsConstructor
@AllArgsConstructor
@Setter
@ToString
@EqualsAndHashCode
@Entity
@Table(name = "dept_emp", catalog = "employees")
public class DeptEmp implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "empNo", column = @Column(name = "emp_no", nullable = false)),
            @AttributeOverride(name = "deptNo", column = @Column(name = "dept_no", nullable = false, length = 4))})
    private DeptEmpId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dept_no", nullable = false, insertable = false, updatable = false)
    private Departments departments;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_no", nullable = false, insertable = false, updatable = false)
    private Employees employees;

    @Temporal(TemporalType.DATE)
    @Column(name = "from_date", nullable = false, length = 10)
    private Date fromDate;

    @Temporal(TemporalType.DATE)
    @Column(name = "to_date", nullable = false, length = 10)
    private Date toDate;
}
