package com.ems.entity;
// Generated Aug 11, 2019 12:49:44 AM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.*;
import lombok.*;

import java.util.Date;

/**
 * DeptManager generated by hbm2java
 */
@Entity
@Table(name = "dept_manager", catalog = "employees")
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
public class DeptManager implements java.io.Serializable {

    private DeptManagerId id;
    private Departments departments;
    private Employees employees;
    private Date fromDate;
    private Date toDate;

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "empNo", column = @Column(name = "emp_no", nullable = false)),
            @AttributeOverride(name = "deptNo", column = @Column(name = "dept_no", nullable = false, length = 4))})
    public DeptManagerId getId() {
        return this.id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dept_no", nullable = false, insertable = false, updatable = false)
    public Departments getDepartments() {
        return this.departments;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_no", nullable = false, insertable = false, updatable = false)
    public Employees getEmployees() {
        return this.employees;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "from_date", nullable = false, length = 10)
    public Date getFromDate() {
        return this.fromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "to_date", nullable = false, length = 10)
    public Date getToDate() {
        return this.toDate;
    }
}
