package com.ems.entity;
// Generated Aug 11, 2019 12:49:44 AM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import lombok.*;

/**
 * DeptManagerId generated by hbm2java
 */

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Embeddable
public class DeptManagerId implements java.io.Serializable {

    private int empNo;
    private String deptNo;

    @Column(name = "emp_no", nullable = false)
    public int getEmpNo() {
        return this.empNo;
    }

    @Column(name = "dept_no", nullable = false, length = 4)
    public String getDeptNo() {
        return this.deptNo;
    }

    /*
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeptManagerId castOther))
			return false;

        return (this.getEmpNo() == castOther.getEmpNo())
				&& ((this.getDeptNo() == castOther.getDeptNo()) || (this.getDeptNo() != null
						&& castOther.getDeptNo() != null && this.getDeptNo().equals(castOther.getDeptNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmpNo();
		result = 37 * result + (getDeptNo() == null ? 0 : this.getDeptNo().hashCode());
		return result;
	}
    */

}
