package com.ems.entity;
// Generated Aug 11, 2019 12:49:44 AM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.*;
import lombok.*;

import java.util.Date;

/**
 * Employees generated by hbm2java
 */

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Entity
@Table(name = "employees", catalog = "employees")
public class Employees_temp implements java.io.Serializable {
    @Id
    @Column(name = "emp_no", unique = true, nullable = false)
    private int empNo;

    @Temporal(TemporalType.DATE)
    @Column(name = "birth_date", nullable = false, length = 10)
    private Date birthDate;
    @Column(name = "first_name", nullable = false, length = 14)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 16)
    private String lastName;

    @Column(name = "gender", nullable = false, length = 1)
    private char gender;

    @Temporal(TemporalType.DATE)
    @Column(name = "hire_date", nullable = false, length = 10)
    private Date hireDate;

    /*
     * @OneToMany(fetch = FetchType.LAZY, mappedBy = "employees") public Set<Titles>
     * getTitleses() { return this.titleses; }
     *
     * public void setTitleses(Set<Titles> titleses) { this.titleses = titleses; }
     *
     * @OneToMany(fetch = FetchType.LAZY, mappedBy = "employees") public
     * Set<Salaries> getSalarieses() { return this.salarieses; }
     *
     * public void setSalarieses(Set<Salaries> salarieses) { this.salarieses =
     * salarieses; }
     *
     * @OneToMany(fetch = FetchType.LAZY, mappedBy = "employees") public
     * Set<DeptEmp> getDeptEmps() { return this.deptEmps; }
     *
     * public void setDeptEmps(Set<DeptEmp> deptEmps) { this.deptEmps = deptEmps; }
     *
     * @OneToMany(fetch = FetchType.LAZY, mappedBy = "employees") public
     * Set<DeptManager> getDeptManagers() { return this.deptManagers; }
     *
     * public void setDeptManagers(Set<DeptManager> deptManagers) {
     * this.deptManagers = deptManagers; }
     *
     */
}
