package com.ems.entity;
// Generated Aug 11, 2019 12:49:44 AM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.*;
import lombok.*;

import java.util.Date;

/**
 * Salaries generated by hbm2java
 */

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Entity
@Table(name = "salaries", catalog = "employees")
public class Salaries implements java.io.Serializable {
    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "empNo", column = @Column(name = "emp_no", nullable = false)),
            @AttributeOverride(name = "fromDate", column = @Column(name = "from_date", nullable = false, length = 10))})
    private SalariesId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_no", nullable = false, insertable = false, updatable = false)
    private Employees employees;

    @Column(name = "salary", nullable = false)
    private int salary;

    @Temporal(TemporalType.DATE)
    @Column(name = "to_date", nullable = false, length = 10)
    private Date toDate;
}
