package com.ems.entity;
// Generated Aug 11, 2019 12:49:44 AM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import lombok.*;

import java.util.Date;

/**
 * TitlesId generated by hbm2java
 */

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@ToString
@EqualsAndHashCode
@Embeddable
public class TitlesId implements java.io.Serializable {
    @Column(name = "emp_no", nullable = false)
    private int empNo;

    @Column(name = "title", nullable = false, length = 50)
    private String title;

    @Column(name = "from_date", nullable = false, length = 10)
    private Date fromDate;

    /*
        public boolean equals(Object other) {
            if ((this == other))
                return true;
            if ((other == null))
                return false;
            if (!(other instanceof TitlesId castOther))
                return false;

            return (this.getEmpNo() == castOther.getEmpNo())
                    && ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
                            && castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
                    && ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
                            && castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
        }

        public int hashCode() {
            int result = 17;

            result = 37 * result + this.getEmpNo();
            result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
            result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
            return result;
        }
    */

}
