logging:
  file:
    name: logs/application.log
  level:
    com:
      ems: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    root: ERROR
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{MMddyyyy}.%i.log.gz
  pattern:
    console: '%d{yyyy-MM-dd}|%d{HH:mm:ss.SSS}|%-10.30thread|${spring.application.name},%X{traceId:-},%X{spanId:-}|%5p|
      %-50.50logger{100}| %m%n'
    file: '%d{yyyy-MM-dd}|%d{HH:mm:ss.SSS}|%-10.30thread|${spring.application.name},%X{traceId:-},%X{spanId:-}|%5p|
      %-50.50logger{100}| %m%n'
server:
  error:
    include-stacktrace: never
  port: 9090
spring:
  application:
    name: EMS
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:employees
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: DETECT
  security:
    user:
      password: admin
